-- Application seed data required by the PostgreSQL exam service.
-- Source: server/src/data/seed.js (examStructure), verified against server/data/acet.sqlite.

INSERT INTO exam_blueprint (id, payload)
VALUES (
  1,
  $exam_blueprint$[{"subjectTitle":"Abstract Reasoning","allottedTimeSec":420,"questions":[{"type":"mcq","stem":"Find the next figure pattern: square, triangle, circle, square, triangle, ...","choiceOpts":["Square","Triangle","Circle","Pentagon"],"answerIdx":2},{"type":"mcq","stem":"Which item best completes the sequence: 3, 6, 12, 24, ...","choiceOpts":["30","36","42","48"],"answerIdx":3},{"type":"mcq","stem":"A folded paper is punched once at the center. When opened twice, how many holes appear?","choiceOpts":["1","2","4","8"],"answerIdx":2}]},{"subjectTitle":"Mathematics","allottedTimeSec":600,"questions":[{"type":"mcq","stem":"If 3x + 7 = 22, what is x?","choiceOpts":["3","4","5","6"],"answerIdx":2},{"type":"mcq","stem":"A triangle has angles 45 and 65 degrees. What is the third angle?","choiceOpts":["60","70","80","90"],"answerIdx":1},{"type":"mcq","stem":"What is 15% of 240?","choiceOpts":["24","30","36","42"],"answerIdx":2}]},{"subjectTitle":"English and General Knowledge","allottedTimeSec":540,"questions":[{"type":"mcq","stem":"Identify the error: The board of directors are expected to announce the merger tomorrow.","choiceOpts":["The board","are","to announce","No error"],"answerIdx":1},{"type":"mcq","stem":"Republic Act No. 9184 is primarily concerned with:","choiceOpts":["Data Privacy","Government Procurement","Cybercrime","Civil Service Rules"],"answerIdx":1},{"type":"mcq","stem":"Who wrote The Indolence of the Filipinos?","choiceOpts":["Andres Bonifacio","Apolinario Mabini","Jose Rizal","Emilio Jacinto"],"answerIdx":2}]},{"subjectTitle":"Logical Reasoning","allottedTimeSec":600,"questions":[{"type":"mcq","stem":"All A are B. Some B are C. Therefore, some A are C. This syllogism is:","choiceOpts":["Valid","Invalid: undistributed middle","Invalid: illicit major","Cannot be determined"],"answerIdx":1},{"type":"mcq","stem":"If it rains, the ground gets wet. The ground is wet. Therefore, it rained. What fallacy is this?","choiceOpts":["Ad hominem","Denying the antecedent","Affirming the consequent","Straw man"],"answerIdx":2},{"type":"mcq","stem":"Which is the contrapositive of: If I study, I will pass?","choiceOpts":["If I pass, I studied","If I do not study, I will not pass","If I do not pass, I did not study","I will pass if I study"],"answerIdx":2}]},{"subjectTitle":"Ateneo Essay","allottedTimeSec":900,"questions":[{"type":"essay","stem":"Ateneo emphasizes Magis, or doing more for others. Describe a specific instance where you went beyond expectations to assist your community."}]}]$exam_blueprint$::jsonb
)
ON CONFLICT (id) DO UPDATE SET payload = EXCLUDED.payload;
